# Range Normalization


In [2]:
import numpy as np
from sklearn import preprocessing

features = np.array([[-500.5],
[-100.1],
[0],
[100.1],
[900.9]])

minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))

scaled_feature = minmax_scale.fit_transform(features)

print(scaled_feature)

[[0.        ]
 [0.28571429]
 [0.35714286]
 [0.42857143]
 [1.        ]]


# Standart Deviation Normalization

In [3]:
import numpy as np
from sklearn import preprocessing

features = np.array([[-1000.1],
[-200.2],
[500.5],
[600.6],
[9000.9]])

mean = np.mean(features)
std = np.std(features)

sd_scale = preprocessing.StandardScaler()

scaled_feature = sd_scale.fit_transform(features)

mean_scaled = np.mean(scaled_feature)
std_scaled = np.std(scaled_feature)

print(scaled_feature)
print(mean)
print(std)
print(mean_scaled)
print(std_scaled)


[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
1780.3399999999997
3655.6709067420165
4.4408920985006264e-17
1.0


# Robust Scaling

import numpy as np
from sklearn.preprocessing import RobustScaler

features = np.array([
    [10],
    [12],
    [13],
    [15],
    [1000]
])

robust_scaler = RobustScaler()

scaled_features = robust_scaler.fit_transform(features)

print(scaled_features)

#RobustScaler outlier değerleri silmez veya sınırlandırmaz.
#Sadece ölçeklendirme parametrelerinin aykırı değerlerden daha az etkilenmesini sağlar.

# Normalizing Observations
## Her satırı kendi içinde normalize etme

In [4]:
import numpy as np
from sklearn.preprocessing import Normalizer

features = np.array([
    [0.5, 0.5],
    [1.1, 3.4],
    [1.5, 20.2],
    [1.63, 34.4],
    [10.9, 3.3]
])

normalizer = Normalizer(norm="l2")
normalized_features = normalizer.fit_transform(features)
print(normalized_features)

[[0.70710678 0.70710678]
 [0.30782029 0.95144452]
 [0.07405353 0.99725427]
 [0.04733062 0.99887928]
 [0.95709822 0.28976368]]


# Detecting Outliers (IQR Method)

In [5]:
import numpy as np

features = np.array([
    [10],
    [12],
    [11],
    [13],
    [15],
    [14],
    [1000],
    [-100]
])

Q1 = np.percentile(features, 25)
Q3 = np.percentile(features, 75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = features[(features < lower_bound) | (features > upper_bound)]

print(outliers)

[1000 -100]


# Deleting Missing Values

In [6]:
import numpy as np
import pandas as pd

features = np.array([[1.1, 11.1],
[2.2, 22.2],
[3.3, 33.3],
[4.4, 44.4],
[np.nan, 55]])

df = pd.DataFrame(features)
df = df.dropna(axis=0)#eksik değer olan satırı siler
print(df)

     0     1
0  1.1  11.1
1  2.2  22.2
2  3.3  33.3
3  4.4  44.4


# Fill in missing values(Mean Imputation)

In [7]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

features = np.array([[1.1, 11.1],
[2.2, 22.2],
[3.3, 33.3],
[4.4, 44.4],
[np.nan, 55]])

imputer = SimpleImputer(strategy="mean")
'''
"mean"	Ortalama ile doldurur
"median"	Medyan ile doldurur
"most_frequent"	En sık geçen değerle doldurur
"constant"	Belirlediğimiz sabit değerle doldurur
'''
features_imputed = imputer.fit_transform(features)

print(features_imputed)


[[ 1.1  11.1 ]
 [ 2.2  22.2 ]
 [ 3.3  33.3 ]
 [ 4.4  44.4 ]
 [ 2.75 55.  ]]


# Discretizing Features (Binning)

In [8]:
import numpy as np

age = np.array([6, 12, 20, 36, 65])

age_binary = (age >= 18).astype(int)

print(age_binary)

[0 0 1 1 1]


# One-Hot Encoding
## Nominal veriler için uygundur

In [9]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

features = np.array([
    ["Texas"],
    ["California"],
    ["Texas"],
    ["Delaware"],
    ["Texas"]
])

encoder = OneHotEncoder(sparse_output=False)
encoded_features = encoder.fit_transform(features)#Her bir kategorik değer için bir sütun oluşturuyoruz

print(encoded_features)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Encoding Ordinal Features

In [10]:
import pandas as pd

dataframe = pd.DataFrame({
    "Score": [
        "Low",
        "Low",
        "Medium",
        "Medium",
        "High"
    ]
})

mapping = {
        "Low" : 0,
        "Medium" : 1,
        "High" : 2
    }

dataframe["Encoding_Dataframe"] = dataframe["Score"].map(mapping)
print(dataframe)

    Score  Encoding_Dataframe
0     Low                   0
1     Low                   0
2  Medium                   1
3  Medium                   1
4    High                   2


# Dictionary to Feature Matrix

In [14]:
from sklearn.feature_extraction import DictVectorizer

data_dict = [
    {"Red": 2, "Blue": 4},
    {"Red": 4, "Blue": 3},
    {"Red": 1, "Yellow": 2},
    {"Red": 2, "Yellow": 2}
]

vectorizer = DictVectorizer(sparse=False)

feature_matrix = vectorizer.fit_transform(data_dict)

print(vectorizer.get_feature_names_out())
print(feature_matrix)

['Blue' 'Red' 'Yellow']
[[4. 2. 0.]
 [3. 4. 0.]
 [0. 1. 2.]
 [0. 2. 2.]]


# Predicting Missing Categorical Values With KNN

In [21]:
import numpy as np
import pandas as pd

from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

df = pd.DataFrame({
    "Age": [20, 25, 45, 50, 22, 48],
    "Income": [2000, 3000, 7000, 8000, 2500, 7500],
    "Category": [
        "Budget", "Budget",
        "Premium", "Premium",
        np.nan, np.nan
    ]
})

known = df[df["Category"].notna()]#Eksik olmayan değerleri seçer.
missing = df[df["Category"].isna()]#Eksik değerleri seçer.

X_train = known[["Age", "Income"]]
y_train = known["Category"]

X_missing = missing[["Age", "Income"]]

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_missing_scaled = scaler.transform(X_missing)#yeni gözlemlerin de eğitim verisinden öğrendiğimiz aynı ortalama ve standart sapmayla dönüştürülmesi gerekiyor.

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train_scaled, y_train)

predictions = knn.predict(X_missing_scaled)

df.loc[df["Category"].isna(), "Category"] = predictions

print(df)

   Age  Income Category
0   20    2000   Budget
1   25    3000   Budget
2   45    7000  Premium
3   50    8000  Premium
4   22    2500   Budget
5   48    7500  Premium


# Undersampling, Oversampling and SMOTE

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

iris = load_iris()

X = iris.data
y = iris.target

print(np.unique(y, return_counts=True))#hangi sınıftan kaç tane var?

# Setosa sınıfından ilk 10 örneği al
setosa_indices = np.where(y == 0)[0][:10]

# Diğer iki sınıfın bütün örneklerini al
other_indices = np.where(y != 0)[0]

# İndeksleri birleştir
indices = np.concatenate([setosa_indices, other_indices])

X_imbalanced = X[indices]

# Setosa = 0, Not Setosa = 1
y_imbalanced = (y[indices] != 0).astype(int)

print(np.unique(y_imbalanced, return_counts=True))

#Undersampling
under_sampler = RandomUnderSampler(random_state=42)

X_under, y_under = under_sampler.fit_resample(
    X_imbalanced,
    y_imbalanced
)

print(np.unique(y_under, return_counts=True))

#Oversampling(Potansiyel overfitting riski)
over_sampler = RandomOverSampler(random_state=42)

X_over, y_over = over_sampler.fit_resample(
    X_imbalanced,
    y_imbalanced
)

print(np.unique(y_over, return_counts=True))

#SMOTE(en yakın n komşudan sentetik örnekler oluşturur)
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42, k_neighbors=3)

X_smote, y_smote = smote.fit_resample(
    X_imbalanced,
    y_imbalanced
)

print(np.unique(y_smote, return_counts=True))

(array([0, 1, 2]), array([50, 50, 50]))
(array([0, 1]), array([ 10, 100]))
(array([0, 1]), array([10, 10]))
(array([0, 1]), array([100, 100]))
(array([0, 1]), array([100, 100]))
