# Row Vector ve Column Vector

In [6]:
import numpy as np

row_vector = np.array([[1,2,3]])
column_vector = np.array([[1],[2],[3]])


print("Row vector:", row_vector)
print("Row shape:", row_vector.shape)

print("Column vector:", column_vector)
print("Column shape:", column_vector.shape)


Row vector: [[1 2 3]]
Row shape: (1, 3)
Column vector: [[1]
 [2]
 [3]]
Column shape: (3, 1)


# linspace()

In [13]:
 import numpy as np

 rand_num = np.linspace(3,100,30)
 print(rand_num)

[  3.           6.34482759   9.68965517  13.03448276  16.37931034
  19.72413793  23.06896552  26.4137931   29.75862069  33.10344828
  36.44827586  39.79310345  43.13793103  46.48275862  49.82758621
  53.17241379  56.51724138  59.86206897  63.20689655  66.55172414
  69.89655172  73.24137931  76.5862069   79.93103448  83.27586207
  86.62068966  89.96551724  93.31034483  96.65517241 100.        ]


# Two Dimensional Array

In [20]:
import numpy as np

array = np.array([[1, 2], [3, 4], [5, 6]])
print(array.shape)
print(array.size)
print(array.ndim)


(3, 2)
6
2


# Sparse Matrix

In [24]:
import numpy as np
from scipy.sparse import csr_matrix

t_array = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

sparse_matrix = csr_matrix(t_array)
print(sparse_matrix)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


# Array Operations

In [60]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5, 6])

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

#array[start:stop:step]
print("A)",vector[1:4])
print("B)",vector[:3])
print("C)",vector[3:])
print("D)",vector[-1])

#Bonus
print("Bonus)",vector[-2:])


print("E)",matrix[:,1])
print("F)",np.max(matrix))
print("F)",np.min(matrix))
print("F)",np.mean(matrix))
print("F)",np.var(matrix))
print("F)",np.std(matrix))
print("G)Column max:", np.max(matrix, axis=0))
print("G)Row max:", np.max(matrix, axis=1))
print("H)",matrix.T)

A) [2 3 4]
B) [1 2 3]
C) [4 5 6]
D) 6
Bonus) [5 6]
E) [2 5 8]
F) 9
F) 1
F) 5.0
F) 6.666666666666667
F) 2.581988897471611
G)Column max: [7 8 9]
G)Row max: [3 6 9]
H) [[1 4 7]
 [2 5 8]
 [3 6 9]]


# NumPy Broadcasting

In [62]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

new_matrix = matrix + 100
print(new_matrix)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


# Reshape

In [77]:
import numpy as np

matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
[10, 11, 12]])

new_matrix = matrix.reshape(2,6)
print(new_matrix)
print(new_matrix.shape)
print(matrix.reshape(-1,1))#Ben sütunu seçiyorum, satırı sen hesapla mantığıyla

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


# Number Generation

In [85]:
import numpy as np

random_float = np.random.rand(3)
print(random_float)

random_ints = np.random.randint(1, 11, 3)
print(random_ints)

random_normal = np.random.normal(loc=0.0, scale=1.0,size=3)
print(random_normal)

[0.55401599 0.03551852 0.40716487]
[4 6 3]
[-0.15064944  0.55443807 -1.07763913]


# Dataframe


In [103]:
import numpy as np
import pandas as pd

weather_matrix = np.linspace(5,30,15).reshape(5,3)
print("A) ",weather_matrix)

weather_matrix_dataframe = pd.DataFrame(weather_matrix, index=["day1", "day2", "day3", "day4", "day5"], columns=["s1", "s2", "s3"])
print("B) ",weather_matrix_dataframe)

rowSums = weather_matrix_dataframe.sum(axis=1)
print("C) ",rowSums.idxmax())
print(rowSums.max())

subB = weather_matrix_dataframe.loc[["day4","day5"],["s2","s3"]]
print("D) ",subB)


A)  [[ 5.          6.78571429  8.57142857]
 [10.35714286 12.14285714 13.92857143]
 [15.71428571 17.5        19.28571429]
 [21.07142857 22.85714286 24.64285714]
 [26.42857143 28.21428571 30.        ]]
B)               s1         s2         s3
day1   5.000000   6.785714   8.571429
day2  10.357143  12.142857  13.928571
day3  15.714286  17.500000  19.285714
day4  21.071429  22.857143  24.642857
day5  26.428571  28.214286  30.000000
C)  day5
84.64285714285714
D)               s2         s3
day4  22.857143  24.642857
day5  28.214286  30.000000


# DataFrame-2

In [119]:
import numpy as np
import pandas as pd

name = (["Ali","Cenk","Mete"])
age = ([26,32,29])
salary = ([2700, 4900, 3200])

company = pd.DataFrame({"Name":name,"Age":age,"Salary":salary})
print(company)

highest_salary = 0
highest_salary_name = ""

for i in range(len(company)):#satır sayısı kadar
    if(company.loc[i, "Salary"]>highest_salary):
        highest_salary = company.loc[i, "Salary"]
        highest_salary_name = company.loc[i, "Name"]
        
print(highest_salary_name ,"earns", highest_salary)


   Name  Age  Salary
0   Ali   26    2700
1  Cenk   32    4900
2  Mete   29    3200
Cenk earns 4900
